name: debug-drive

services:
  app:
    container_name: filestash
    image: machines/filestash:latest
    restart: unless-stopped
    environment:
    - APPLICATION_URL=
    - CANARY=true
    - OFFICE_URL=http://wopi_server:9980
    - OFFICE_FILESTASH_URL=http://app:8334
    - OFFICE_REWRITE_URL=http://127.0.0.1:9980
    ports:
    - "8334:8334"
    volumes:
    - filestash_data:/app/data/state/

  wopi_server:
    container_name: filestash_wopi
    image: collabora/code:24.04.10.2.1
    restart: unless-stopped
    environment:
    - "extra_params=--o:ssl.enable=false"
    - aliasgroup1="https://.*:443"
    command:
    - /bin/bash
    - -c
    - |
         curl -o /usr/share/coolwsd/browser/dist/branding-desktop.css https://gist.githubusercontent.com/mickael-kerjean/bc1f57cd312cf04731d30185cc4e7ba2/raw/d706dcdf23c21441e5af289d871b33defc2770ea/destop.css
         /bin/su -s /bin/bash -c '/start-collabora-online.sh' cool
    user: root
    ports:
    - "9980:9980"

  dufs:
    container_name: dufs
    image: sigoden/dufs
    command: --auth admin:admin@/:rw --allow-all /webdav-data
    ports:
      - "5000:5000"
    volumes:
      - dufs_data:/webdav-data
    restart: unless-stopped

volumes:
    filestash_data: {}
    dufs_data: {}
